services:
  backend:
    build:
      context: ./backend

    container_name: spreadview-backend

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend

    container_name: spreadview-frontend

    ports:
      - "8080:80"

    depends_on:
      - backend